"""first

Revision ID: a05a99b7da08
Revises:
Create Date: 2024-06-04 15:09:40.691895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a05a99b7da08"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("base", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("agencies_pkey")),
    )
    op.create_table(
        "rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency_from", sa.String(), nullable=False),
        sa.Column("currency_to", sa.String(), nullable=False),
        sa.Column("rate", sa.Numeric(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("agency_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name=op.f("rates_agency_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rates_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rates")
    op.drop_table("agencies")
    # ### end Alembic commands ###
