Table rate {
  id integer [primary key]
  agency_id integer [ref: > agency.id]
  to_currency varchar(3)
  rate float
  created_at timestamp
  updated_at timestamp
}

Table agency {
  id integer [primary key]
  name varchar
  base_currency varchar(3)
  created_at timestamp
  updated_at timestamp
}
